version: '3.7'

services:

  tracker:
    build: ./tracker
    entrypoint: "./flighttracker.py -m mqtt  -l ${LAT} -L ${LONG} -a ${ALT} -P skyscan/planes/json -T skyscan/flight/json -M ${MIN_ELEVATION} -c ${CAMERA_LEAD}"
    depends_on:
      - mqtt
    restart: unless-stopped

  adsb-mqtt:
    build: ./adsb-mqtt
    entrypoint: "./adsb-mqtt.py -H piaware -m mqtt  -t skyscan/planes/json"
    volumes:
      - ./data:/app/data
    depends_on:
      - mqtt
      - piaware
    restart: unless-stopped

#  pan-tilt-pi:
#    build: ./pan-tilt-pi
#    entrypoint: "./camera.py -m mqtt -t skyscan/flight/json"
#    volumes:
#      - /opt/vc:/opt/vc
#      - ./capture:/app/capture
#    devices:
#      - /dev/i2c-1:/dev/i2c-1       
#      - "/dev/vchiq:/dev/vchiq" 
#    environment: 
#      - LD_LIBRARY_PATH=/opt/vc/lib
#    privileged: true
#    depends_on:
#      - mqtt

  axis-ptz:
    build: ./axis-ptz
    entrypoint: "./camera.py -m mqtt -t skyscan/flight/json -u ${AXIS_USERNAME} -p ${AXIS_PASSWORD} -a ${AXIS_IP} -z ${CAMERA_ZOOM} -s ${CAMERA_MOVE_SPEED} -d ${CAMERA_DELAY}"
    volumes:
      - ./capture:/app/capture
    depends_on:
      - mqtt
    restart: unless-stopped
      
  piaware:
    build: ./piaware
    tty: true
    container_name: piaware
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8080:80
      - 30003:30003
      - 30005:30005
    environment:
      - TZ=${TZ}
      - LAT=${LAT}
      - LONG=${LONG}
      - FEEDER_ID=${FEEDER_ID}
      - RECEIVER_TYPE=rtlsdr
      - DUMP1090_DEVICE=${RTL_DEV}
    restart: unless-stopped

  tar1090:
    image: mikenye/tar1090:latest
    tty: true
    container_name: tar1090
    restart: always
    environment:
      - TZ=${TZ}
      - BEASTHOST=piaware
      - MLATHOST=piaware
      - LAT=${LAT}
      - LONG=${LONG}
    networks:
      - adsbnet
    ports:
      - 8078:80
    tmpfs:
      - /run:exec,size=64M
      - /var/log
  mqtt:
    build: ./mqtt
    ports:
        - "9001:9001"
        - "1883:1883"
    restart: unless-stopped

  egi:
    build: ./egi
    entrypoint: bash -c "gpsd ${GPS_SERIAL} -F /var/run/gpsd.sock && python3 egi_mqtt.py -m mqtt -l ${LAT} -L ${LONG} -a ${ALT} -r ${ROLL} -p ${PITCH} -y ${YAW}"
    devices:
      - /dev/ttyACM0
    depends_on:
      - mqtt
    restart: unless-stopped