version: '3.7'
services: 

  jupyter: 
    # image: tensorflow/tensorflow:2.5.0-gpu-jupyter
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports: 
      - 8888:8888
    # entrypoint: "jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='$(cat /run/secrets/login_info)'"
    secrets: 
      - login_info

secrets: 
  login_info: 
    file: ./password.txt
      #command: /bin/bash -c "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=''" //does that get the password info?
