version: '3.7'
services: 

  jupyter: 
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports: 
      - 8888:8888
    secrets: 
      - login_info

secrets: 
  login_info: 
    file: ./loginInfo.txt
