services:
  jupyter:
    build: ./jupyter
    command: /bin/bash -c "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    ports:
      - 8888:8888
      - 6006:6006
      - 6007:6007
      - 5151:5151
    volumes:
      - /home/ubuntu/efs:/tf/efs
      - /home/ubuntu/efs/model-export:/tf/model-export 
      - /home/ubuntu/efs/dataset-export:/tf/dataset-export
      - ./notebooks:/tf/notebooks
      - ./testing:/tf/testing
      - /home/ubuntu/efs/media:/tf/media
      - /home/ubuntu/efs/fiftyone-db:/root/.fiftyone 
      - /home/ubuntu/efs/models:/tf/models
      - /home/ubuntu/efs/training:/tf/training
      - /home/ubuntu/efs/data:/tf/data
      - ./scripts:/tf/scripts
    restart: always
    
