services:
  jupyter:
    build: ./jupyter
    command: /bin/bash -c "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    ports:
      - 8888:8888
      - 6006:6006
      - 6007:6007
      - 5151:5151
    volumes:
      - ./model-export:/tf/model-export 
      - ./dataset-export:/tf/dataset-export
      - ./notebooks:/tf/notebooks
      - ./testing:/tf/testing
      - ./media:/tf/media
      - ./fiftyone-db:/root/.fiftyone 
      - ./models:/tf/models
      - ./training:/tf/training
      - ./scripts:/tf/scripts
    restart: always
    